[package]
name = "udp_ipv6_multicast"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = "1"
turmoil = { path = "../.." }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
